### PR TITLE
Feature to add motor failure capability in gazebo_motor_model plugin

### PR DESCRIPTION
**Pull request by siddhu45**
This modification in the `gazebo_motor_model` plugin will enable to simulate motor failure in the robot model in real time by subscribing to a rostopic `/gazebo/motor_failure/motor_number` and fail that motor by setting the `motor_constant_ = 0`. 

Any suggestions to make the code better are welcome. And if someone could contribute to making the rotor visually stop rotating when it fails, that would be great. 
Please review @TSC21

Thanks!

PS: Sorry for the rookie mistake, but I haven't created a PR before how do you commit changes and add the changes I made? Meanwhile, the updated files are [here](https://drive.google.com/open?id=1k9k-CS4tap69AKupuDwEOT6GTzBu1Vj0)
Thanks

### CODE REVIEW

**Comment by TSC21** [comment]
@siddhu45 this PR is wrong. You have to apply it against `PX4/sitl_gazebo` and not `Dronecode/sitl_gazebo`.

**Comment by siddhu45** [comment]
Ok.  I will try to do that. Can you show me the instructions to do so. And
I will close this one and open a new one in px4 sitl_gazebo. Thanks

**Comment by TSC21** [comment]
You just have to do it the same way you opened the PR for Dronecode. Just fork https://github.com/PX4/sitl_gazebo, clone it to your computer, create a new branch, apply the changes, commit, and open a new pull request against https://github.com/PX4/sitl_gazebo.

**Comment by siddhu45** [comment]
Ok. Great! Thanks for the info. I will do that and try to put up by this weekend.

**Pull request closed without merging**
